services:
  app_tests:
    image: tests
    build:
      context: .
      dockerfile: Dockerfile.testing
    depends_on:
      - host_test

  redis-cache:
    image: redis:alpine
    hostname: redis-cache
    container_name: redis-cache
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server

  host_test:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASSWORD_TEST}
      - POSTGRES_DB=${DB_NAME_TEST}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER_TEST} -d ${DB_NAME_TEST}"]
      interval: 5s
      timeout: 5s
      retries: 5
