services:
  app:
    image: nella611/menus
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - .:/srv/application/menus_ylab
    entrypoint: "/srv/application/menus_ylab/docker-entrypoint.dev.sh"