"""change size char

Revision ID: e1f879d0adfd
Revises: d0adbbc46efa
Create Date: 2023-08-14 09:44:20.842150

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e1f879d0adfd'
down_revision = 'd0adbbc46efa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
