"""added discount

Revision ID: db0cc72330c6
Revises: e1f879d0adfd
Create Date: 2023-08-16 09:46:52.572208

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'db0cc72330c6'
down_revision = 'e1f879d0adfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'discount')
    # ### end Alembic commands ###
