"""init

Revision ID: 235bf8fc6c6d
Revises: 
Create Date: 2023-07-30 14:42:46.744732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235bf8fc6c6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
